name-template: v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION
template: |
  ## What’s Changed

  $CHANGES

categories:
  - title: 🚀 New Features
    when:
      labels:
        - new-feature
  - title: 🐛 Bug Fixes
    when:
      labels:
        - bug
  - title: 📖 Documentation
    when:
      labels:
        - docs
  - title: 📦 Dependency updates
    when:
      labels:
        - dependencies
