name: build

on:
  push:
    branches:
      - main

jobs:
  selenoid-ui:
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: auto
    steps:
      - uses: actions/checkout@v6

      - name: Set Golang
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'
          check-latest: true
          cache: true

      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: ui/yarn.lock

      - name: Test
        run: ci/test.sh
        env:
          GOTOOLCHAIN: auto

      - name: Build
        run: ci/build.sh

      - name: Latest image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        run: ci/docker-push.sh latest

      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
