name: build

on:
  push:
    branches:
      - main

jobs:
  selenoid-ui:
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: auto
    steps:
      - uses: actions/checkout@v7

      - name: Set Golang
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: ui/yarn.lock

      - name: Test
        run: ci/test.sh
        env:
          GOTOOLCHAIN: auto

      - name: Build
        run: ci/build.sh
        env:
          VITE_HUB_ACCESS_KEY: ${{ secrets.HUB_ACCESS_KEY }}
          VITE_HUB_AUTH_USER: ${{ secrets.HUB_AUTH_USER }}
          VITE_HUB_AUTH_PASS: ${{ secrets.HUB_AUTH_PASS }}

      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
